# this is for doing pull request previews so we can let the non-devs
# check out the changes before we merge and deploy to s3
# as such, we basically tell it to ignore production deploys and only
# run pull request deploy previews
[build]
  publish = "frontend/dist/"
  command = "npm run build-frontend"

# Production context: when ignore returns an exit code of 0
# this tells netlify to skip the build. We always skip the production
# build since prod is really done via s3
[context.production]
  ignore = "exit 0"

[context.deploy-preview]
  command = "npm run build-frontend-for-cypress"