name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

        # only install dependencies using
        # https://github.com/cypress-io/github-action
        # will restore / create folders
        #   ~/.npm
        #   ~/.cache/Cypress
      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

  linter:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Run linter 👀
        run: npm run lint

  unit-tests:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Run unit tests 🧪
        run: npm test

  integration-tests:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Run Integration tests 💻
        run: npm run test:integration
